# Generated by Django 5.2.1 on 2025-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_candidate_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="current_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="current_job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience",
            field=models.IntegerField(
                blank=True, help_text="Total years of experience", null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated skills (e.g., Python, Django, AWS, SQL)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
