# Generated by Django 5.2.1 on 2025-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0003_alter_candidate_current_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
