# Generated by Django 4.2.21 on 2025-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0004_alter_education_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer-not-to-say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
